# 把 DIR 下的所有文件转成单个 C++ 源文件 OUT
#
# 用法：
#   cmake -DDIR=/path/to/web/dist -DOUT=/path/to/embedded_assets.cpp \
#         -P scripts/gen_embedded_assets.cmake
#
# 生成：
#   - 每个文件一个 const unsigned char[] + size_t length
#   - 一个全局 std::array 查找表：path → { data ptr, size, mime }
#
# bagu serve 通过 lookup_embedded_asset(path) 取回数据。
# 找不到时（SPA 路由），调用方应 fallback 到 /index.html。

if(NOT DIR OR NOT OUT)
    message(FATAL_ERROR "DIR and OUT are required")
endif()

if(NOT IS_DIRECTORY "${DIR}")
    message(FATAL_ERROR "DIR=${DIR} is not a directory")
endif()

file(GLOB_RECURSE FILES RELATIVE "${DIR}" "${DIR}/*")
list(SORT FILES)
list(LENGTH FILES NUM_FILES)

# ---------- 头部 ----------
file(WRITE "${OUT}" "// AUTO-GENERATED by scripts/gen_embedded_assets.cmake. DO NOT EDIT.\n")
file(APPEND "${OUT}" "// Source dir: ${DIR}\n")
file(APPEND "${OUT}" "// Files: ${NUM_FILES}\n\n")
file(APPEND "${OUT}" "#include \"http/embedded_assets.h\"\n\n")
file(APPEND "${OUT}" "namespace bagu::http {\n\n")
file(APPEND "${OUT}" "namespace {\n\n")

# 简单 mime 表（按扩展）
function(infer_mime FILE_NAME OUT_VAR)
    string(TOLOWER "${FILE_NAME}" LOWER)
    if(LOWER MATCHES "\\.html$")
        set(${OUT_VAR} "text/html; charset=utf-8" PARENT_SCOPE)
    elseif(LOWER MATCHES "\\.js$" OR LOWER MATCHES "\\.mjs$")
        set(${OUT_VAR} "application/javascript; charset=utf-8" PARENT_SCOPE)
    elseif(LOWER MATCHES "\\.css$")
        set(${OUT_VAR} "text/css; charset=utf-8" PARENT_SCOPE)
    elseif(LOWER MATCHES "\\.json$")
        set(${OUT_VAR} "application/json; charset=utf-8" PARENT_SCOPE)
    elseif(LOWER MATCHES "\\.svg$")
        set(${OUT_VAR} "image/svg+xml" PARENT_SCOPE)
    elseif(LOWER MATCHES "\\.png$")
        set(${OUT_VAR} "image/png" PARENT_SCOPE)
    elseif(LOWER MATCHES "\\.jpg$" OR LOWER MATCHES "\\.jpeg$")
        set(${OUT_VAR} "image/jpeg" PARENT_SCOPE)
    elseif(LOWER MATCHES "\\.ico$")
        set(${OUT_VAR} "image/x-icon" PARENT_SCOPE)
    elseif(LOWER MATCHES "\\.woff2$")
        set(${OUT_VAR} "font/woff2" PARENT_SCOPE)
    elseif(LOWER MATCHES "\\.woff$")
        set(${OUT_VAR} "font/woff" PARENT_SCOPE)
    elseif(LOWER MATCHES "\\.txt$")
        set(${OUT_VAR} "text/plain; charset=utf-8" PARENT_SCOPE)
    elseif(LOWER MATCHES "\\.webmanifest$")
        set(${OUT_VAR} "application/manifest+json; charset=utf-8" PARENT_SCOPE)
    else()
        set(${OUT_VAR} "application/octet-stream" PARENT_SCOPE)
    endif()
endfunction()

# 把字符串转成合法 C++ 标识符
function(make_ident STR OUT_VAR)
    string(REGEX REPLACE "[^a-zA-Z0-9_]" "_" RES "${STR}")
    set(${OUT_VAR} "_asset_${RES}" PARENT_SCOPE)
endfunction()

set(IDX 0)
# 用 string 累加而非 list（list 把 ; 当 element 分隔符，会切碎含 mime 的行）
set(TABLE_STR "")

foreach(REL ${FILES})
    set(FULL "${DIR}/${REL}")
    file(READ "${FULL}" HEX HEX)
    string(LENGTH "${HEX}" HEXLEN)
    math(EXPR FILESIZE "${HEXLEN} / 2")

    make_ident("${REL}" IDENT)
    infer_mime("${REL}" MIME)

    # 把 HEX 转成 0xNN, 0xNN, ... 序列（每行 16 个）
    set(BYTES "")
    set(COUNT 0)
    string(REGEX MATCHALL "[0-9a-fA-F][0-9a-fA-F]" PAIRS "${HEX}")
    foreach(P ${PAIRS})
        string(APPEND BYTES "0x${P},")
        math(EXPR COUNT "${COUNT} + 1")
        math(EXPR MOD16 "${COUNT} % 16")
        if(MOD16 EQUAL 0)
            string(APPEND BYTES "\n")
        endif()
    endforeach()

    file(APPEND "${OUT}" "// ${REL} (${FILESIZE} bytes, ${MIME})\n")
    file(APPEND "${OUT}" "constexpr unsigned char ${IDENT}[] = {\n${BYTES}\n};\n\n")

    string(APPEND TABLE_STR
        "    { \"/${REL}\", ${IDENT}, ${FILESIZE}, \"${MIME}\" },\n")
    math(EXPR IDX "${IDX} + 1")
endforeach()

# ---------- 表 ----------
file(APPEND "${OUT}" "constexpr EmbeddedAsset kAssets[] = {\n")
file(APPEND "${OUT}" "${TABLE_STR}")
file(APPEND "${OUT}" "};\n\n")
file(APPEND "${OUT}" "constexpr size_t kAssetCount = sizeof(kAssets) / sizeof(kAssets[0]);\n\n")

file(APPEND "${OUT}" "}  // namespace\n\n")

# 查找函数
file(APPEND "${OUT}" "const EmbeddedAsset* lookup_embedded_asset(std::string_view path) {\n")
file(APPEND "${OUT}" "    for (size_t i = 0; i < kAssetCount; ++i) {\n")
file(APPEND "${OUT}" "        if (path == kAssets[i].path) return &kAssets[i];\n")
file(APPEND "${OUT}" "    }\n")
file(APPEND "${OUT}" "    return nullptr;\n")
file(APPEND "${OUT}" "}\n\n")

file(APPEND "${OUT}" "size_t embedded_asset_count() { return kAssetCount; }\n\n")
file(APPEND "${OUT}" "}  // namespace bagu::http\n")

message(STATUS "Embedded ${NUM_FILES} files into ${OUT}")
